on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Multi Platform

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install QB64
      run: .ci/install.sh
    - name: Bootstrap compiler
      run: echo "${HOME}/qb64" >> $GITHUB_PATH
    - name: Compile
      run: qb64 BSTAC.BAS -o BSTAC
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.11.2
      with:
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        bodyFile: release_text.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/PyES.deb
        asset_name: PyES-${{ github.ref }}.deb
        tag: ${{ github.ref }}
        overwrite: true

#   macos-build:
#     runs-on: macos-latest
#     if: "!contains(github.event.head_commit.message, 'ci-skip')"
#     steps:
#     - uses: actions/checkout@v2
#     - name: Bootstrap compiler
#       run: .ci/bootstrap.sh osx
#     - name: Compile
#       run: .ci/compile.sh
#     - name: Publish
#       if: github.event_name == 'push'
#       run: .ci/deploy.sh osx
#     - name: Upload
#       uses: actions/upload-artifact@v3
#       with: 
#         name: qb64_${{ github.ref_name }}_${{ github.sha }}_osx
#         path: /Users/runner/work/qb64/qb64_*.tar.gz

#   windows-x86-build:
#     runs-on: windows-latest
#     env:
#       PLATFORM: x86
#     steps:
#     - uses: actions/checkout@v3
#     - name: Install QB64
#       run: .ci/bootstrap32.bat
#     - name: Compile
#       run: .ci/compile.bat
#     - name: Publish
#       if: github.event_name == 'push'
#       run: .ci/deploy.ps1
#     - name: Upload
#       uses: actions/upload-artifact@v3
#       if: always()
#       with: 
#         name: qb64_${{ github.ref_name }}_${{ github.sha }}_win-x86
#         path: D:\a\qb64\qb64_*.7z

#   windows-x64-build:
#     runs-on: windows-latest
#     if: "!contains(github.event.head_commit.message, 'ci-skip')"
#     env:
#       PLATFORM: x64
#     steps:
#     - uses: actions/checkout@v2
#     - name: Bootstrap compiler
#       run: .ci/bootstrap.bat
#     - name: Compile
#       run: .ci/compile.bat
#     - name: Publish
#       if: github.event_name == 'push'
#       run: .ci/deploy.ps1
#     - name: Upload
#       uses: actions/upload-artifact@v3
#       with: 
#         name: qb64_${{ github.ref_name }}_${{ github.sha }}_win-x64
#         path: D:\a\qb64\qb64_*.7z

# # ${{ github.event.repository.updated_at }}
# # path: ${{ github.workspace }}\qb64_*.7z