
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Multi Platform

jobs:
  create-release:
    permissions:
        contents: write
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release # Creates the release, assets will be added after building
        id: create_release
        uses: ncipollo/release-action@v1.11.2
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          bodyFile: release_text.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  linux-build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install QB64
      run: .ci/install.sh
    - name: Compile BSTAC
      run: ./qb64/qb64 -xq BSTAC.BAS -o BSTAC
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: qb64/BSTAC
        asset_name: BSTAC-${{ github.ref }}-lnx
        tag: ${{ github.ref }}
        overwrite: true

  macos-build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install QB64
      run: .ci/install.sh macos
    - name: Compile BSTAC
      run: ./qb64/qb64 -xq BSTAC.BAS -o BSTAC
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: qb64/BSTAC
        asset_name: BSTAC-${{ github.ref }}-macos
        tag: ${{ github.ref }}
        overwrite: true

  windows-build:
    runs-on: windows-latest
    env:
      PLATFORM: x64
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install QB64
      run: .ci/install.cmd
    - name: Compile BSTAC
      run: ./qb64/qb64.exe -xq BSTAC.BAS -o BSTAC.exe
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: qb64/BSTAC.exe
        asset_name: BSTAC-${{ github.ref }}-win.exe
        tag: ${{ github.ref }}
        overwrite: true

  rollback-release:
    name: Rollback
    if: ${{ failure() }}
    needs: [linux-build, macos-build, windows-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Rollback
        uses: author/action-rollback@stable
        with:
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}